[ENH] Validate filter tags in list_models and list_datasets (#2956)
# The following checklist is mandatory.

Your PR will be closed if you remove the checklist or do not answer the
questions to a satisfactory level. Use of LLM is **strictly forbidden**
for any part of this checklist (even for improving language).

### Your checklist for this pull request

- [x] Have you followed all the steps from our [Contributing
Guide](https://github.com/pgmpy/pgmpy/blob/dev/Contributing.md)?
- [x] Does the PR fully address the linked issue and is within its
defined scope? If you are still working on the PR, mark it as draft.
- [x] Are all the GitHub Actions checks passing? If not, mark your PR as
draft while you fix it.

Please answer the following questions:

- Did you use an LLM for any assistance? Please describe how and what
you used it for?
Yes, I used an LLM to help check my approach and assist with writing
some of the tests.
- What steps have you taken to verify that the changes correctly address
the issue? And what edge cases have you considered?
I added tests and also checked the changes in the Python REPL to confirm
that invalid tags raise an error and valid filters still work.
- Has the LLM added try-except blocks? They will need to be removed; any
error handling must be explicit.
No try-except blocks are added
- Have you used LLM for generating tests? They need to be compressed
into a smaller number of tests without reducing coverage.
yes and there are only small tests added 

### Issue number(s) that this pull request fixes
- Fixes #2920 

### List of changes to the codebase in this pull request
Previously, passing an incorrect filter tag would silently return an
empty list. This PR adds validation for filter tags in `list_models` and
`list_datasets` and raises a `ValueError` when unrecognized tags are
provided. The tests are also added for the behaviour

```
(venv) kajal@kajal-HP-Pavilion-Laptop-15-eh2xxx:~/pgmpy$ python
Python 3.12.3 (main, Jan 22 2026, 20:57:42) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
Ctrl click to launch VS Code Native REPL
>>> from pgmpy.example_models import list_models
>>> from pgmpy.datasets import list_datasets
>>> list_models(n_nodes=10)
['bnrep/APSsystem', 'bnrep/argument', 'bnrep/gonorrhoeae', 'bnrep/greencredit', 'bnrep/lawschool', 'bnrep/liquefaction', 'bnrep/liquidity', 'bnrep/nuclearwaste', 'bnrep/salmonella2', 'bnrep/seismic', 'bnrep/tbm']
>>> list_models(is_paraterized=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kajal/pgmpy/pgmpy/example_models/_base.py", line 215, in list_models
    raise ValueError(
ValueError: Unrecognized filter argument(s): ['is_paraterized']. Valid filter tags are: ['is_continuous', 'is_discrete', 'is_hybrid', 'is_parameterized', 'n_edges', 'n_nodes', 'name'].
>>> list_models(num_nodes=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kajal/pgmpy/pgmpy/example_models/_base.py", line 215, in list_models
    raise ValueError(
ValueError: Unrecognized filter argument(s): ['num_nodes']. Valid filter tags are: ['is_continuous', 'is_discrete', 'is_hybrid', 'is_parameterized', 'n_edges', 'n_nodes', 'name'].
>>> list_models(is_paraterized=True, n_nodez=10, unknown_arg="test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kajal/pgmpy/pgmpy/example_models/_base.py", line 215, in list_models
    raise ValueError(
ValueError: Unrecognized filter argument(s): ['is_paraterized', 'n_nodez', 'unknown_arg']. Valid filter tags are: ['is_continuous', 'is_discrete', 'is_hybrid', 'is_parameterized', 'n_edges', 'n_nodes', 'name'].
>>> 
```